config/routes.rb
Rails.application.routes.draw do
    root 'homes#top'
    root to: 'homes#top'
    get 'home/about' => 'homes#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
    resources :books
    resources :users, only: [:show, :edit, :update, :index]
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

    #バリデーション
	validates :title, presence: true, length: { maximum: 200 }
    validates :body, presence: true, length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
# ログイン済ユーザーのみにアクセスを許可する
before_action :authenticate_user!

  def index
  	   @books = Book.page(params[:page]).reverse_order
  	   @book = Book.new
  end

  def show
  	  @book = Book.find(params[:id])
  end

  def new
  	  @book = Book.new
      @book = Book.all
  end

  def create
  	  @book = Book.new(book_params)
  	  @book.user_id = current_user.id
      if @book.save
        flash[:notice] = "Book was successfully created."
  	    redirect_to book_path(@book)
      else
        @books = Book.page(params[:page]).reverse_order
        render 'index'
    end
  end

  def edit
      @book = Book.find(params[:id])
      if @book.user.id != current_user.id
         redirect_to books_path
      end
  end

  def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
         flash[:notice] = "Book was successfully updated."
         redirect_to book_path(@book)
      else
         @books = Book.page(params[:page]).reverse_order
         render 'index'
      end
  end

  def destroy
      @book = Book.find(params[:id])
      @book.destroy
      flash[:notice] = "Book was successfully destroyed."
      redirect_to books_path
  end

private

   def book_params
   	   params.require(:book).permit(:title, :body, :user_id)
   end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<h2>New book</h2>
     <!--form_for部分-->
     <%= form_for(book) do |f| %>
 	       <% if book.errors.any? %>
 	           <div id="error_explanation">
 	               <h2><%= pluralize(book.errors.count, "book") %>
 	               prohibied this error from being saved: </h2>

 	               <% @book.errors.full_messages.each do |message| %>
                     <li><%= message %></li>
                 <% end %>
             </div>
         <% end %>

         <div class="field">
             <%= f.label :title %>
             <%= f.text_field :title, class: "form-control" %>
         </div>

         <div class="field" >
             <%= f.label :Opinion %>
             <%= f.text_area :body, class: "form-control" %></br>
         </div>

    　　　<div class="action">
             <button type="submit" class="btn btn-primary btn-md btn-block"> Create Book</button>
        </div>
    <% end %>

app/views/books/_list_2.html.erb
<h1>Books</h1>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
        </tr>
    </thead>
    <tbody>
        <% books.each do |book| %>
            <tr>
                <td>
                    <%= link_to (attachment_image_tag book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb"), user_path(book.user) %>
                </td>
 	              <td><%= link_to book.title, book_path(book) %></td>
 	              <td><%= book.body %></td>
 	          </tr>
        <% end %>
        <%= paginate books %>
 	  </tbody>
</table>

app/views/books/edit.html.erb
<div class= "container">
    <div class= "row">
        <div class="col-md-6 col-md-offset-3">

            <h1>Editing Book</h1>
                <!-- form_for部分 -->
                <%= form_for(@book) do |f| %>
                    <% if @book.errors.any? %>
                        <div id="error_explanation">
                             <h2><%= pluralize(@book.errors.count, "book") %>
                              prohibied this error from being saved: </h2>
                            <% @book.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                        </div>
                    <% end %>

                    <div class="field">
                        <%= f.label :title %>
                        <%= f.text_field :title, class: "form-control" %>
                    </div>
                    <div class="field" >
                        <%= f.label :Opinion %>
                        <%= f.text_area :body, class: "form-control" %></br>
                    </div>

                    <div class="action">
                        <button type="submit" class="btn btn-primary btn-md btn-block"> Update Book</button>
                    </div>
                <% end %>
            <%= link_to 'Show', book_path(@book)%> |
            <%= link_to 'Back', books_path %>
        </div>
    </div>
</div>

app/views/books/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-3">
            <h1>User info</h1>
                <table class="table">
                    <tr>
                        <%= attachment_image_tag current_user, :profile_image, :fill, 90, 90, format: 'jpeg', fallback: "no_image.jpg" %>
                    </tr>
                    <tr>
                        <th>Name</th>
	                      <th><%= current_user.name %></th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th><%= current_user.introduction %></th>
                    </tr>
                </table>

                <%= link_to edit_user_path(current_user) do %>
                    <button type="button" class="btn btn-default btn-md btn-block">
                        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                    </button>
                <% end %>

                <div class="row">
                    <div class="col-xs-12">
                        <%= render 'books/list', book: @book %>
                    </div>
                </div>
        </div>

                <div class="col-xs-9">
                    <%= render 'books/list_2', books: @books %>
                </div>
    </div>
</div>

app/views/books/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-3">
            <h1>User info</h1>
                <table class="table">
                    <tr>
                        <%= attachment_image_tag @book.user, :profile_image, :fill, 90, 90, format: 'jpeg', fallback: "no_image.jpg" %>
                    </tr>

                    <tr>
                        <th>Name</th>
                        <th><%= @book.user.name %></th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th><%= @book.user.introduction %></th>
                    </tr>
                </table>

                <%= link_to edit_user_path(@book.user) do %>
                    <button type="button" class="btn btn-default btn-md btn-block">
                        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                    </button>
                <% end %>

                <div class="row">
                    <div class="col-xs-12">
                        <%= render 'books/list', book: Book.new %>
                    </div>
                </div>
        </div>

                <div class="col-xs-9">
                    <h2>Book detail</h2>
                        <table class='table'>
                            <tr>
                                <td><%= link_to  @book.user.name, user_path(current_user.id) %>
                                    <%= link_to (attachment_image_tag @book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb"),user_path(@book.user) %>
                                </td>
                                <td><%= @book.title %></td>
                                <td><%= @book.body %></td>
                                <td>
                                    <% if @book.user == current_user %>
                                        <%= link_to "Edit",edit_book_path(@book),class:"btn btn-success" %> </td>
                                    <% end %>
                                </td>
                                <td>
                                    <% if @book.user == current_user %>
                                        <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "Are you sure?",class:"btn btn-danger"%>
                                    <% end %>
                                </td>
                            </tr>
                        </table>
                </div>
    </div>
</div>