config/routes.rb
Rails.application.routes.draw do
    root 'homes#top'
    root to: 'homes#top'
    get 'home/about' => 'homes#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
    resources :books
    resources :users, only: [:show, :edit, :update, :index]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
        .notice {color: green; margin-left: 20px;}
        #error_explanation {color: red;}
    </style>
  </head>

  <body>
      <nav class="navbar navbar-inverse" style="border-radius: 0px">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample7">
              <span class="sr-only">Toggle navigation</span>
              <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand" style="padding:0px 0px 10px 20px">
                <span>Bookers</span>
            </div>
          </div>

          <div id="slidemenu">
              <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
                  <% if user_signed_in? %>
                      <li class="">
                          <%= link_to user_path(current_user.id) do %>
                              <span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span>
                          <% end %>
                      </li>
                      <li class="">
                          <%= link_to users_path do %>
                              <span class="glyphicon glyphicon-user" aria-hidden="true"> Users</span>
                          <% end %>
                      </li>
                      <li class="">
                          <%= link_to  books_path do %>
                              <span class="glyphicon glyphicon-book" aria-hidden="true"> Books</span>
                          <% end %>
                      </li>
                      <li class="">
                          <%= link_to destroy_user_session_path, method: :delete do %>
                              <span class="glyphicon glyphicon-share" aria-hidden="true"> logout</span>
                          <% end %>
                      </li>
                  <% else %>
                      <li class="">
                          <%= link_to  root_path do %>
                              <span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span>
                          <% end %>
                      </li>
                      <li class="">
                          <%= link_to home_about_path do %>
                              <span class="glyphicon glyphicon-link" aria-hidden="true"> About</span>
                          <% end %>
                      </li>
                      <li class="">
                          <%= link_to new_user_registration_path do %>
                              <span class="glyphicon glyphicon-edit" aria-hidden="true"> sign up</span>
                          <% end %>
                      </li>
                      <li class="">
                          <%= link_to new_user_session_path do %>
                              <span class="glyphicon glyphicon-log-in" aria-hidden="true"> login</span>
                          <% end %>
                      </li>
                  <% end %>
              </ul>
          </div>
        </div>
      </nav>

      <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <%= yield %>

      <div class='container'>
          <div class='row'>
              <div class='col-xs-3 col-xs-offset-9'>
                  <p>CopyRight Infratop.inc</p>
              </div>
          </div>
      </div>
  </body>
</html>